# Generated by Django 3.0.1 on 2020-06-13 10:22

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200613_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/', upload_to=cart.models.directory),
        ),
    ]
